# Generated by Django 5.2.11 on 2026-02-19 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(help_text='Max no. of people allowed')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='accounts.gym')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('gym', 'name'), name='unique_room_per_gym')],
            },
        ),
    ]
